PX-Enterprise:
  BRANCH_VERSION_CONFIG: 2.6=2.6,2.5=2.5,2.4=2.4,2.3=2.3,2.2=2.2,2.1=2.1,2.0.3=2.0,1.7=1.7
  LATEST_VERSION: 2.6
  PRODUCT_NAME: Portworx Enterprise
  PRODUCT_INDEX_NAME: PX-Enterprise
  VERSIONS_BASE_URL: docs.portworx.com
  OTHER_PRODUCT_NAMES_AND_INDICES: PX-Backup=PX-Backup-1-1
  NGINX_REDIRECTS_FILE: px-enterprise-redirects.conf
  MANIFESTS_DIRECTORY: "themes/pxdocs-tooling/deploy/manifests/"
  BUILDER_IMAGE_PREFIX: "pxdocs:"
  SEARCH_INDEX_IMAGE_PREFIX: "pxdocs-indexer:"
PX-Backup:
  BRANCH_VERSION_CONFIG: 1.1=1.1,1.0=1.0
  LATEST_VERSION: 1.1
  PRODUCT_NAME: PX-Backup
  PRODUCT_INDEX_NAME: PX-Backup
  VERSIONS_BASE_URL: backup.docs.portworx.com
  OTHER_PRODUCT_NAMES_AND_INDICES: "Portworx Enterprise=PX-Enterprise-2-6"
  NGINX_REDIRECTS_FILE: px-backup-redirects.conf
  MANIFESTS_DIRECTORY: "themes/pxdocs-tooling/deploy/manifests/pxbackup/"
  BUILDER_IMAGE_PREFIX: "pxbackup:"
  SEARCH_INDEX_IMAGE_PREFIX: "pxbackup-indexer:"